name: On Pull Request(Elixir)

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.ex'
      - '**/*.exs'

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.15.6
      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile
      - name: Check format
        run: mix format --check-formatted
      - name: Check type format
        run: mix dialyzer
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_LEVEL: warning
        run: |
          mix credo suggest --strict --format=flycheck | reviewdog -efm="%f:%l:%c: %t: %m" -efm="%f:%l: %t: %m" -name="credo" -level="${INPUT_LEVEL}" -filter-mode=nofilter
  unit-test:
    runs-on: ubuntu-22.04
    needs:
      - linter
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.15.6
      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile
      - name: Run tests
        run: mix test