name: On Pull Request(Elixir)

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.ex'
      - '**/*.exs'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-22.04
    env:
      PLT_CACHE_PATH: priv/plts
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.15.6
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: make setup
      - name: Check format
        run: make format
      - name: Retrieve PLT Cache
        uses: actions/cache@v3
        id: plt-cache
        with:
          path: ${{ env.PLT_CACHE_PATH }}
          key: ${{ runner.os }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.PLT_CACHE_PATH }}
          make ${{ env.PLT_CACHE_PATH }}/dialyzer.plt
      - name: Check type format
        run: make dialyzer
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_LEVEL: warning
        run: |
          mix credo suggest --strict --format=flycheck | reviewdog -efm="%f:%l:%c: %t: %m" -efm="%f:%l: %t: %m" -name="credo" -level=${{ env.INPUT_LEVEL }} -filter-mode=nofilter
  unit-test:
    runs-on: ubuntu-22.04
    needs:
      - linter
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.15.6
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: make setup
      - name: Run tests
        run: make test